server:
  persistentVolume:
    enabled: false
  retention: "15d"
  global:
    scrape_interval: 30s
    evaluation_interval: 30s

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
