apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  sources:
    # Source 1: Rancher Helm Chart
    - chart: rancher
      repoURL: https://releases.rancher.com/server-charts/stable
      targetRevision: 2.13.0
      helm:
        releaseName: rancher
        valueFiles:
          - $values/gitops/apps/rancher/values.yaml
    
    # Source 2: Git repo with values and IngressRoute
    - repoURL: https://github.com/bioyeneye/home-lab-k8s.git
      targetRevision: main
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m