grafana:
  enabled: true
  adminPassword: admin123
  service:
    type: NodePort
    nodePort: 32000

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
