apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  users: |
    admin:$apr1$BWF28uYb$GMUIBiN7/DL65ECzhN5Wf.
