apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dashboard-auth
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  basicAuth:
    secret: traefik-dashboard-auth
